// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcwqicxonfklppqyemtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjd3FpY3hvbmZrbHBwcXllbXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTU3MzQsImV4cCI6MjA2OTczMTczNH0.hf1d7jILOMg3PhM1AqNvjMlUrZG90LmYwdal0FMKDbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});